version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "immobot-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1525ewcjsl1l0"
s3_prefix = "immobot-api"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=536200232045.dkr.ecr.eu-west-1.amazonaws.com/immobotapi7181c6d3/helloworldfunction19d43fc4repo"]
