version: '3'
services:

  mongodb:
    image: mongo:5.0.3
    volumes:
      - ./mongodb/data/db/:/data/db
    ports:
    - 27017:27017

  crawler_app:
    build:
      dockerfile: docker/Dockerfile
      context: ./crawler_app/
    working_dir: /app/
    volumes:
    - ./crawler_app/app/:/app
    depends_on:
    - mongodb