version: '3'
services:

  mongodb:
    image: mongo:5.0.3
    volumes:
      - ./mongodb/data/db/:/data/db
    ports:
      - 27017:27017

  crawler-app:
    build:
      dockerfile: docker/Dockerfile
      context: crawler-app/
    working_dir: /app/
    volumes:
      - ./crawler-app/app/:/app
    depends_on:
      - mongodb
      - ebay-mock
    environment:
#      EBAY_HOST: http://ebay-mock/
      EBAY_HOST: https://www.ebay-kleinanzeigen.de/
      MONGODB_NAME: second-hand-bikes-pipeline
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017

  ebay-mock:
    image: openjdk:11
    working_dir: /app
#    hostname: ebay-mock
    command: "java -jar ./karate.jar -m /app/features/search.feature -p 80"
    ports:
      - 8080:80
    volumes:
      - ./ebay-mock/app:/app

  postgres:
    image: postgres:alpine3.14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}
      PGPASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432

  transformer-app:
    build:
      dockerfile: docker/Dockerfile
      context: transformer-app/
    working_dir: /app/
    volumes:
      - ./transformer-app/app/:/app
    depends_on:
      - mongodb
      - postgres
    environment:
      MONGODB_NAME: second-hand-bikes-pipeline
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}

  notifier-app:
    build:
      dockerfile: docker/Dockerfile
      context: transformer-app/
    working_dir: /app/
    volumes:
      - ./notifier-app/app/:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}