version: '3'
services:

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/tweet_collector/
    depends_on:
    - mongodb


  mongodb:
    image: mongo
    ports:
    - "27018:27017"


  airflow:
    image: puckel/docker-airflow
    ports:
    - "8081:8080"
    volumes:
    - ./airflow/dags/:/usr/local/airflow/dags/
    - ./airflow/requirements.txt:/requirements.txt
    command: ["webserver", "scheduler"]
    environment:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgresdb:5432/airflow
    depends_on:
    - mongodb
    - postgresdb

## Substitute airflow for the etl_job service
  # etl_job:
  #   build: etl_job/
  #   volumes:
  #   - ./etl_job/:/etl_job/
  #   depends_on:
  #   - mongodb
  #   - postgresdb


  postgresdb2:
    image: postgres
    ports:
    - "5556:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres


  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=airflow
    - POSTGRES_PASSWORD=airflow
    - POSTGRES_DB=airflow


  slack_bot:
    build: slack_bot/
    volumes:
    - ./slack_bot/:/slack_bot/
    depends_on:
    - postgresdb
