version: '3'
services:

  mongodb:
    image: mongo:5.0.3
    volumes:
      - efs-immobot-mongodb-volume:/data/db
    ports:
      - 27017:27017

  crawler-app:
    image: 536200232045.dkr.ecr.eu-west-1.amazonaws.com/immobot-crawler-repository:latest
    working_dir: /app/
    depends_on:
      - mongodb
    environment:
      EBAY_HOST: https://www.ebay-kleinanzeigen.de/
      MONGODB_NAME: immobot-pipeline
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017

#  database:
#    image: 536200232045.dkr.ecr.eu-west-1.amazonaws.com/immobot-postgres-repository:latest
#    environment:
#      PGDATA: /data/postgres
#      PGPASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}
#      POSTGRES_DB: ${POSTGRES_DBNAME}
#    ports:
#      - 5432:5432

  transformer-app:
    image: 536200232045.dkr.ecr.eu-west-1.amazonaws.com/immobot-transformer-repository:latest
    working_dir: /app/
    depends_on:
      - mongodb
#      - postgres
    environment:
      MONGODB_NAME: immobot-pipeline
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}

  notifier-app:
    image: 536200232045.dkr.ecr.eu-west-1.amazonaws.com/immobot-notifier-repository:latest
    working_dir: /app/
#    depends_on:
#      - postgres
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_pass_changeme}

volumes:
  efs-immobot-mongodb-volume: